FROM node:12

# ENV DEBUG true

RUN mkdir /var/ergo
COPY ./pool /var/ergo
WORKDIR /var/ergo
RUN DEBIAN_FRONTEND='noninteractive' apt-get update
RUN DEBIAN_FRONTEND='noninteractive' apt-get upgrade -y
RUN DEBIAN_FRONTEND='noninteractive' apt-get install -y --no-install-recommends \
    python3 \
    git \
    make \
    gcc \
    g++ \
    nano \
    && rm -rf /var/lib/apt/lists/*

RUN npm rebuild
RUN npm i -g nodemon

ENTRYPOINT node init.js
