FROM openjdk

# ENV DEBUG true

# json cli parser
# RUN apt-get update && apt-get install -y jq 

# ergo node config
RUN mkdir /var/ergo
COPY ./node/ergo-4.0.13.jar /var/ergo/ergo.jar
COPY ./node/testnet.conf /var/ergo/ergo.conf
WORKDIR /var/ergo

ENTRYPOINT java -jar ergo.jar --testnet -c ergo.conf
